In [3]:
import pandas as pd

df = pd.read_excel("../data/raw/Projects_Report.xlsx")

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst rows:")
display(df.head())

print("\nMissing values:")
print(df.isnull().sum())

Shape: (1733, 13)

Columns:
['Projects Details ', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

First rows:

,Projects Details,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,Original Cost\n(in cr.),Revised Cost\n(in cr.),Expenditure\n(in cr.),Physical Progress\n(in %),Original\nDate of Commissioning,Revised\nDate of Commissioning,Sanction Date
2,1,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],706718,C/o NITB Imphal Airport,499,499,215.1,54,13/07/2024,31/12/2026,01/11/2021
3,2,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],432726,"Construction of 8 Nos. RETs for Runway 07-25, ...",480,0,9.68,4,15/01/2028,NaN,16/07/2024
4,3,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701121,Construction of New Domestic Terminal Building...,347,0,190.89,97,13/08/2025,31/10/2026,30/12/2022

Missing values:
Projects Details       1
Unnamed: 1             1
Unnamed: 2             1
Unnamed: 3             1
Unnamed: 4             1
Unnamed: 5             1
Unnamed: 6             1
Unnamed: 7             1
Unnamed: 8             1
Unnamed: 9             1
Unnamed: 10            1
Unnamed: 11          304
Unnamed: 12            3
dtype: int64

In [4]:
import pandas as pd
import numpy as np

# Load Excel with the correct header row
file_path = "../data/raw/Projects_Report.xlsx"

df = pd.read_excel(file_path, header=1)

# Clean column names
df.columns = (
    df.columns
    .astype(str)
    .str.strip()
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
)

print("Shape:", df.shape)

print("\nColumns:")
for col in df.columns:
    print(col)

print("\nFirst 5 rows:")
display(df.head())

Shape: (1732, 13)

Columns:
Unnamed: 0
Unnamed: 1
Unnamed: 2
Unnamed: 3
Unnamed: 4
Unnamed: 5
Unnamed: 6
Unnamed: 7
Unnamed: 8
Unnamed: 9
Unnamed: 10
Unnamed: 11
Unnamed: 12

First 5 rows:

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,Original Cost\n(in cr.),Revised Cost\n(in cr.),Expenditure\n(in cr.),Physical Progress\n(in %),Original\nDate of Commissioning,Revised\nDate of Commissioning,Sanction Date
1,1,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],706718,C/o NITB Imphal Airport,499,499,215.1,54,13/07/2024,31/12/2026,01/11/2021
2,2,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],432726,"Construction of 8 Nos. RETs for Runway 07-25, ...",480,0,9.68,4,15/01/2028,NaN,16/07/2024
3,3,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701121,Construction of New Domestic Terminal Building...,347,0,190.89,97,13/08/2025,31/10/2026,30/12/2022
4,4,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701101,Construction of New Domestic Terminal Building...,1217,1216.9,1216.11,99,31/05/2026,31/08/2026,04/10/2018

In [5]:
df = df.rename(columns={
    "Sr. No.": "sr_no",
    "Sector Name": "sector",
    "Line Ministry": "ministry",
    "Implementing Agency": "agency",
    "Project Code": "project_code",
    "Project Name": "project_name",
    "Original Cost (in cr.)": "original_cost",
    "Revised Cost (in cr.)": "revised_cost",
    "Expenditure (in cr.)": "expenditure",
    "Physical Progress (in %)": "physical_progress",
    "Original Date of Commissioning": "original_completion",
    "Revised Date of Commissioning": "revised_completion",
    "Sanction Date": "sanction_date"
})

print(df.columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

In [6]:
numeric_cols = [
    "original_cost",
    "revised_cost",
    "expenditure",
    "physical_progress"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numeric_cols].dtypes)

KeyError: 'original_cost'

In [7]:
print(df.columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

In [8]:
import pandas as pd

file_path = "../data/raw/Projects_Report.xlsx"

# Row 3 in Excel = index 2 in pandas
df = pd.read_excel(file_path, header=2)

# Clean column names
df.columns = (
    df.columns
    .astype(str)
    .str.strip()
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

Shape: (1731, 13)

Columns:
['Sr. No.', 'Sector Name', 'Line Ministry', 'Implementing Agency', 'Project Code', 'Project Name', 'Original Cost (in cr.)', 'Revised Cost (in cr.)', 'Expenditure (in cr.)', 'Physical Progress (in %)', 'Original Date of Commissioning', 'Revised Date of Commissioning', 'Sanction Date']

,Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,Original Cost (in cr.),Revised Cost (in cr.),Expenditure (in cr.),Physical Progress (in %),Original Date of Commissioning,Revised Date of Commissioning,Sanction Date
0,1,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],706718,C/o NITB Imphal Airport,499,499.0,215.10,54,13/07/2024,31/12/2026,01/11/2021
1,2,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],432726,"Construction of 8 Nos. RETs for Runway 07-25, ...",480,0.0,9.68,4,15/01/2028,NaN,16/07/2024
2,3,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701121,Construction of New Domestic Terminal Building...,347,0.0,190.89,97,13/08/2025,31/10/2026,30/12/2022
3,4,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701101,Construction of New Domestic Terminal Building...,1217,1216.9,1216.11,99,31/05/2026,31/08/2026,04/10/2018
4,5,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],612788,Construction of New Domestic Terminal Building...,322,0.0,242.16,98,01/02/2026,15/09/2026,02/06/2023

In [9]:
df = df.rename(columns={
    "Sr. No.": "sr_no",
    "Sector Name": "sector",
    "Line Ministry": "ministry",
    "Implementing Agency": "agency",
    "Project Code": "project_code",
    "Project Name": "project_name",
    "Original Cost (in cr.)": "original_cost",
    "Revised Cost (in cr.)": "revised_cost",
    "Expenditure (in cr.)": "expenditure",
    "Physical Progress (in %)": "physical_progress",
    "Original Date of Commissioning": "original_completion",
    "Revised Date of Commissioning": "revised_completion",
    "Sanction Date": "sanction_date"
})

print(df.columns.tolist())

['sr_no', 'sector', 'ministry', 'agency', 'project_code', 'project_name', 'original_cost', 'revised_cost', 'expenditure', 'physical_progress', 'original_completion', 'revised_completion', 'sanction_date']

In [10]:
numeric_cols = [
    "original_cost",
    "revised_cost",
    "expenditure",
    "physical_progress"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numeric_cols].dtypes)

original_cost          int64
revised_cost         float64
expenditure          float64
physical_progress      int64
dtype: object

In [11]:
df = pd.read_excel("../data/raw/Projects_Report.xlsx", header=2)

In [12]:
print(df.shape)
print(df.columns.tolist())
display(df.head())

(1731, 13)
['Sr. No.', 'Sector Name', 'Line Ministry', 'Implementing Agency', 'Project Code', 'Project Name', 'Original Cost\n(in cr.)', 'Revised Cost\n(in cr.)', 'Expenditure\n(in cr.)', 'Physical Progress\n(in %)', 'Original\nDate of Commissioning', 'Revised\nDate of Commissioning', 'Sanction Date']

,Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,Original Cost\n(in cr.),Revised Cost\n(in cr.),Expenditure\n(in cr.),Physical Progress\n(in %),Original\nDate of Commissioning,Revised\nDate of Commissioning,Sanction Date
0,1,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],706718,C/o NITB Imphal Airport,499,499.0,215.10,54,13/07/2024,31/12/2026,01/11/2021
1,2,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],432726,"Construction of 8 Nos. RETs for Runway 07-25, ...",480,0.0,9.68,4,15/01/2028,NaN,16/07/2024
2,3,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701121,Construction of New Domestic Terminal Building...,347,0.0,190.89,97,13/08/2025,31/10/2026,30/12/2022
3,4,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701101,Construction of New Domestic Terminal Building...,1217,1216.9,1216.11,99,31/05/2026,31/08/2026,04/10/2018
4,5,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],612788,Construction of New Domestic Terminal Building...,322,0.0,242.16,98,01/02/2026,15/09/2026,02/06/2023

In [13]:
df = df.rename(columns={
    "Sr. No.": "sr_no",
    "Sector Name": "sector",
    "Line Ministry": "ministry",
    "Implementing Agency": "agency",
    "Project Code": "project_code",
    "Project Name": "project_name",
    "Original Cost (in cr.)": "original_cost",
    "Revised Cost (in cr.)": "revised_cost",
    "Expenditure (in cr.)": "expenditure",
    "Physical Progress (in %)": "physical_progress",
    "Original Date of Commissioning": "original_completion",
    "Revised Date of Commissioning": "revised_completion",
    "Sanction Date": "sanction_date"
})

print(df.columns.tolist())

['sr_no', 'sector', 'ministry', 'agency', 'project_code', 'project_name', 'Original Cost\n(in cr.)', 'Revised Cost\n(in cr.)', 'Expenditure\n(in cr.)', 'Physical Progress\n(in %)', 'Original\nDate of Commissioning', 'Revised\nDate of Commissioning', 'sanction_date']

In [14]:
df = df.dropna(how="all")

print("Rows after removing empty rows:", len(df))

Rows after removing empty rows: 1731

In [15]:
text_cols = [
    "sector",
    "ministry",
    "agency",
    "project_code",
    "project_name"
]

for col in text_cols:
    df[col] = df[col].astype("string").str.strip()

print(df[text_cols].head())

                               sector                    ministry  \
0  Aviation & Aviation Infrastructure  Ministry of Civil Aviation
1  Aviation & Aviation Infrastructure  Ministry of Civil Aviation
2  Aviation & Aviation Infrastructure  Ministry of Civil Aviation
3  Aviation & Aviation Infrastructure  Ministry of Civil Aviation
4  Aviation & Aviation Infrastructure  Ministry of Civil Aviation

                             agency project_code  \
0  Airport Authority of India [AAI]       706718
1  Airport Authority of India [AAI]       432726
2  Airport Authority of India [AAI]       701121
3  Airport Authority of India [AAI]       701101
4  Airport Authority of India [AAI]       612788

                                        project_name
0                            C/o NITB Imphal Airport
1  Construction of 8 Nos. RETs for Runway 07-25, ...
2  Construction of New Domestic Terminal Building...
3  Construction of New Domestic Terminal Building...
4  Construction of New Domestic Terminal Building...

In [16]:
numeric_cols = [
    "original_cost",
    "revised_cost",
    "expenditure",
    "physical_progress"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numeric_cols].dtypes)

KeyError: 'original_cost'

In [17]:
import pandas as pd
import numpy as np

# 1. Load the Excel file with the correct header row
file_path = "../data/raw/Projects_Report.xlsx"

df = pd.read_excel(file_path, header=2)

# 2. Clean the column names
df.columns = (
    df.columns
    .astype(str)
    .str.strip()
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
)

# 3. Rename columns
df = df.rename(columns={
    "Sr. No.": "sr_no",
    "Sector Name": "sector",
    "Line Ministry": "ministry",
    "Implementing Agency": "agency",
    "Project Code": "project_code",
    "Project Name": "project_name",
    "Original Cost (in cr.)": "original_cost",
    "Revised Cost (in cr.)": "revised_cost",
    "Expenditure (in cr.)": "expenditure",
    "Physical Progress (in %)": "physical_progress",
    "Original Date of Commissioning": "original_completion",
    "Revised Date of Commissioning": "revised_completion",
    "Sanction Date": "sanction_date"
})

# 4. Convert numeric columns
numeric_cols = [
    "original_cost",
    "revised_cost",
    "expenditure",
    "physical_progress"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# 5. Convert date columns
date_cols = [
    "original_completion",
    "revised_completion",
    "sanction_date"
]

for col in date_cols:
    df[col] = pd.to_datetime(
        df[col],
        errors="coerce",
        dayfirst=True
    )

# 6. Remove completely empty rows
df = df.dropna(how="all")

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Shape: (1731, 13)

Columns:
['sr_no', 'sector', 'ministry', 'agency', 'project_code', 'project_name', 'original_cost', 'revised_cost', 'expenditure', 'physical_progress', 'original_completion', 'revised_completion', 'sanction_date']

Data types:
sr_no                           int64
sector                            str
ministry                          str
agency                            str
project_code                    int64
project_name                      str
original_cost                   int64
revised_cost                  float64
expenditure                   float64
physical_progress               int64
original_completion    datetime64[us]
revised_completion     datetime64[us]
sanction_date          datetime64[us]
dtype: object

Missing values:
sr_no                    0
sector                   0
ministry                 0
agency                   0
project_code             0
project_name             0
original_cost            0
revised_cost             0
expenditure              0
physical_progress        0
original_completion      0
revised_completion     303
sanction_date            2
dtype: int64

In [18]:
print(df.isnull().sum())

sr_no                    0
sector                   0
ministry                 0
agency                   0
project_code             0
project_name             0
original_cost            0
revised_cost             0
expenditure              0
physical_progress        0
original_completion      0
revised_completion     303
sanction_date            2
dtype: int64

In [19]:
print("Duplicate project codes:",
      df["project_code"].duplicated().sum())

Duplicate project codes: 0

In [20]:
print("Revised completion missing:", df["revised_completion"].isna().sum())

print("\nExamples:")
display(
    df[df["revised_completion"].isna()][
        [
            "project_code",
            "project_name",
            "original_completion",
            "revised_completion",
            "physical_progress"
        ]
    ].head(10)
)

Revised completion missing: 303

Examples:

,project_code,project_name,original_completion,revised_completion,physical_progress
1,432726,"Construction of 8 Nos. RETs for Runway 07-25, ...",2028-01-15,NaT,4
14,619054,Development of Keshod Airport.,2027-01-31,NaT,49
18,612183,Development of New Civil Enclave at Bihta,2027-03-31,NaT,4
27,400142,Pachwara South Coal Block,2028-09-30,NaT,87
30,616229,AMAL GONDEGAON GHATROHANA EXPN,2029-03-31,NaT,3
31,611864,AMALAGAMATED NTST KUJAMA OCP 8,2030-03-31,NaT,32
32,615185,AMALGAMATED DHANKASA & JAMUNIA,2027-03-31,NaT,67
35,613798,AMERA OC RCE [1.0 MTY],2026-03-31,NaT,42
36,613799,AMGAON OC RCE [1.0 MTY],2026-03-31,NaT,79
37,615916,AMLG GAURI PAUNI EXPANSION OC,2030-03-31,NaT,4

In [21]:
display(
    df[df["sanction_date"].isna()][
        [
            "project_code",
            "project_name",
            "sanction_date",
            "original_completion"
        ]
    ]
)

,project_code,project_name,sanction_date,original_completion
410,706865,Chandorgaon-Cansaulim rail flyover 16 km Umbre...,NaT,2031-03-31
1714,701530,Ken-Betwa Linking Development Project,NaT,2029-03-31

In [22]:
print("Revised Cost = 0:", (df["revised_cost"] == 0).sum())

display(
    df[df["revised_cost"] == 0][
        [
            "project_code",
            "project_name",
            "original_cost",
            "revised_cost",
            "expenditure",
            "physical_progress"
        ]
    ].head(20)
)

Revised Cost = 0: 831

,project_code,project_name,original_cost,revised_cost,expenditure,physical_progress
1,432726,"Construction of 8 Nos. RETs for Runway 07-25, ...",480,0.0,9.68,4
2,701121,Construction of New Domestic Terminal Building...,347,0.0,190.89,97
4,612788,Construction of New Domestic Terminal Building...,322,0.0,242.16,98
5,612787,Construction of New Domestic Terminal Building...,320,0.0,169.11,92
6,612786,Construction of New Domestic Terminal Building...,266,0.0,186.36,83
12,612789,Development of additional RESA on either end o...,485,0.0,246.96,66
14,619054,Development of Keshod Airport.,363,0.0,109.27,49
15,701113,Development of Lal Bahadur Shastri Internation...,2870,0.0,812.14,35
16,612194,Development of New Civil Enclave and associate...,912,0.0,453.47,73
18,612183,Development of New Civil Enclave at Bihta,1413,0.0,19.44,4
19,618977,Development of New Greenfield Airport at Bundi...,1507,0.0,99.47,14
20,701122,Development of New Integrated Civil Enclave at...,579,0.0,245.81,46
22,611602,"Modernization of Chennai Airport, Phase II, Pa...",1207,0.0,368.10,50
23,612791,Re-Construction of Rigid portions of Secondary...,328,0.0,153.75,74
24,611570,SITC of ATM Automation System and ASMGCS [Incl...,500,0.0,399.77,80
25,612793,Widening of basic strip at Western Side of Run...,323,0.0,87.61,36
26,613800,JAGANNATHPUR OC RCE PROJECT,459,0.0,280.03,96
27,400142,Pachwara South Coal Block,2243,0.0,1448.39,87
28,616223,ADASA UG TO OC MINE,316,0.0,209.29,87
29,400148,AMADAND OCP[4.0MTY],869,0.0,333.43,75

In [23]:
over_spend = df[
    df["expenditure"] > df["original_cost"]
]

print("Projects where expenditure > original cost:",
      len(over_spend))

display(
    over_spend[
        [
            "project_code",
            "project_name",
            "original_cost",
            "expenditure",
            "physical_progress"
        ]
    ].head(20)
)

Projects where expenditure > original cost: 176

,project_code,project_name,original_cost,expenditure,physical_progress
11,400010,Construction of Terminal Building & Associated...,480,524.37,93
21,706724,Guwahati Airport New Integrated Terminal Build...,1712,2670.23,100
45,400369,BINA KAKRI AMALGAMATION EXPANS,836,840.16,92
151,602098,Construction of Permanent Campus for IIM Jammu...,425,484.52,96
174,606112,Tezpur University Projects,154,798.42,98
185,709747,Bagodara Solar Power Project,339,376.64,52
186,602579,Buxar Thermal Power Project [1320 MW],10439,13814.00,95
188,602582,Dhaulasidh Hydro Electric Project [66 MW],688,1284.90,81
191,602538,Installation of FGD for 4x210 & 2x250 MW MTPS ...,1037,1146.29,97
197,602593,Luhri Stage-I Hydro Electric Project [210 MW],1811,1981.17,52
200,602525,"Pakal Dul [Drangdhuran] Hydroelectric Project,...",8112,9905.50,87
201,400261,Patratu Thermal Power Station Expansion Projec...,18668,19405.50,92
203,602184,Rammam-III HEPP [3x40 MW],1382,1701.35,60
204,605156,Rangit-IV HE Project [120 MW] executed by Jal ...,938,1726.66,98
208,602096,Subansiri Lower HE Project [2000 MW],6285,26575.20,98
211,602185,Tapovan-Vishnugad HEP [4x130 MW],2978,7887.36,76
214,602195,Vishnugad Pipalkoti Hydro Electric Project [44...,3860,5906.00,82
215,604833,"Andheri Residential Towers, Mumbai",281,294.89,88
223,400301,Multi Product Pipeline from Irugur to Devangonthi,678,1237.73,88
224,701349,Paradip-Numaligarh Crude Oil Pipeline [PNCPL] ...,10228,11236.50,94

In [24]:
output_path = "../data/processed/paimana_cleaned.csv"

df.to_csv(output_path, index=False)

print("Saved successfully:")
print(output_path)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [25]:
from pathlib import Path

# Create processed folder if it doesn't exist
processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

# Save cleaned dataset
output_path = processed_dir / "paimana_cleaned.csv"

df.to_csv(output_path, index=False)

print("Saved successfully:")
print(output_path.resolve())

Saved successfully:
C:\Users\Suramya\Documents\PAIMANA\ml\data\processed\paimana_cleaned.csv